name: CI/CD

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: false

      - name: 📦 Install dependencies
        run: pnpm install

      - name: 💅 Lint code
        run: pnpm run lint

      - name: 🧪 Run tests
        run: pnpm run test
